// <auto-generated />
using System;
using GetEFWorking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GetEFWorking.Migrations
{
    [DbContext(typeof(QueueContext))]
    [Migration("20260223113625_test3")]
    partial class test3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("GetEFWorking.Models.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("GetEFWorking.Models.QueueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("QueueId", "StudentId")
                        .IsUnique();

                    b.ToTable("QueueEntries");
                });

            modelBuilder.Entity("GetEFWorking.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("QueueTeacher", b =>
                {
                    b.Property<int>("QueuesId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeachersId")
                        .HasColumnType("TEXT");

                    b.HasKey("QueuesId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("TeacherQueues", (string)null);
                });

            modelBuilder.Entity("GetEFWorking.Models.Student", b =>
                {
                    b.HasBaseType("GetEFWorking.Models.User");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GetEFWorking.Models.Teacher", b =>
                {
                    b.HasBaseType("GetEFWorking.Models.User");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("GetEFWorking.Models.QueueEntry", b =>
                {
                    b.HasOne("GetEFWorking.Models.Queue", "Queue")
                        .WithMany("QueueEntries")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GetEFWorking.Models.Student", "Student")
                        .WithMany("QueueEntries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GetEFWorking.Models.Teacher", "Teacher")
                        .WithMany("QueueEntries")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Queue");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QueueTeacher", b =>
                {
                    b.HasOne("GetEFWorking.Models.Queue", null)
                        .WithMany()
                        .HasForeignKey("QueuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GetEFWorking.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GetEFWorking.Models.Student", b =>
                {
                    b.HasOne("GetEFWorking.Models.User", null)
                        .WithOne()
                        .HasForeignKey("GetEFWorking.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GetEFWorking.Models.Teacher", b =>
                {
                    b.HasOne("GetEFWorking.Models.User", null)
                        .WithOne()
                        .HasForeignKey("GetEFWorking.Models.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GetEFWorking.Models.Queue", b =>
                {
                    b.Navigation("QueueEntries");
                });

            modelBuilder.Entity("GetEFWorking.Models.Student", b =>
                {
                    b.Navigation("QueueEntries");
                });

            modelBuilder.Entity("GetEFWorking.Models.Teacher", b =>
                {
                    b.Navigation("QueueEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
