// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using simpeltkoapi.Data;

#nullable disable

namespace GetEFWorking.Migrations
{
    [DbContext(typeof(QueueContext))]
    [Migration("20260223085720_Initial3")]
    partial class Initial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("QueueTeacher", b =>
                {
                    b.Property<int>("QueuesId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeachersId")
                        .HasColumnType("TEXT");

                    b.HasKey("QueuesId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("QueueTeacher");
                });

            modelBuilder.Entity("QueueTeacher1", b =>
                {
                    b.Property<int>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("TEXT");

                    b.HasKey("QueueId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("QueueTeacher1");
                });

            modelBuilder.Entity("simpeltkoapi.Models.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("simpeltkoapi.Models.QueueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("QueueEntries");
                });

            modelBuilder.Entity("simpeltkoapi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("simpeltkoapi.Models.Student", b =>
                {
                    b.HasBaseType("simpeltkoapi.Models.User");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("simpeltkoapi.Models.Teacher", b =>
                {
                    b.HasBaseType("simpeltkoapi.Models.User");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("QueueTeacher", b =>
                {
                    b.HasOne("simpeltkoapi.Models.Queue", null)
                        .WithMany()
                        .HasForeignKey("QueuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simpeltkoapi.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QueueTeacher1", b =>
                {
                    b.HasOne("simpeltkoapi.Models.Queue", null)
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simpeltkoapi.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("simpeltkoapi.Models.Student", b =>
                {
                    b.HasOne("simpeltkoapi.Models.User", null)
                        .WithOne()
                        .HasForeignKey("simpeltkoapi.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("simpeltkoapi.Models.Teacher", b =>
                {
                    b.HasOne("simpeltkoapi.Models.User", null)
                        .WithOne()
                        .HasForeignKey("simpeltkoapi.Models.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
